channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8.2
  - pip=21.0
  - pip:
    - appdirs==1.4.4
    - attrs==20.3.0
    - Authlib==0.15.3
    - backports.zoneinfo==0.2.1
    - beautifulsoup4==4.9.3
    - cached-property==1.5.2
    - cachetools==4.2.1
    - certifi==2020.12.5
    - cffi==1.14.4
    - chardet==3.0.4
    - click==7.1.2
    - cryptography==3.3.1
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dnspython==2.1.0
    - docutils==0.16
    - et-xmlfile==1.0.1
    - exchangelib==3.3.2
    - fpdf==1.7.2
    - free-proxy==1.0.2
    - furl==2.1.0
    - google-api-core==1.25.1
    - google-api-python-client==1.12.8
    - google-auth==1.24.0
    - google-auth-httplib2==0.0.4
    - google-auth-oauthlib==0.4.2
    - google-cloud-core==1.5.0
    - google-cloud-language==1.3.0
    - google-cloud-speech==1.3.2
    - google-cloud-storage==1.35.0
    - google-cloud-texttospeech==1.0.1
    - google-cloud-translate==2.0.2
    - google-cloud-videointelligence==1.16.1
    - google-cloud-vision==1.0.0
    - google-crc32c==1.1.2
    - google-resumable-media==1.2.0
    - googleapis-common-protos==1.52.0
    - graphviz==0.13.2
    - grpcio==1.35.0
    - httplib2==0.18.1
    - idna==2.10
    - isodate==0.6.0
    - jdcal==1.4.1
    - jsonpath-ng==1.5.2
    - jsonschema==3.2.0
    - loguru==0.5.3
    - lxml==4.6.2
    - mss==6.1.0
    - netsuitesdk==1.12.0
    - notifiers==1.2.1
    - ntlm-auth==1.5.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - openpyxl==3.0.6
    - orderedmultidict==1.0.1
    - pandas==1.2.1
    - pdfminer.six==20201018
    - Pillow==8.1.0
    - ply==3.11
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - Pygments==2.7.4
    - pynput-robocorp-fork==2.0.0
    - PyPDF2==1.26.0
    - pyperclip==1.8.1
    - pyrsistent==0.17.3
    - PySocks==1.7.1
    - python-dateutil==2.8.1
    - python-xlib==0.29
    - pytz==2020.5
    - requests==2.25.1
    - requests-file==1.5.1
    - requests-ntlm==1.1.0
    - requests-oauthlib==1.3.0
    - requests-toolbelt==0.9.1
    - rfc3987==1.3.8
    - robotframework==3.2.2
    - robotframework-pythonlibcore==2.2.1
    - robotframework-requests==0.7.2
    - robotframework-seleniumlibrary==4.5.0
    - robotframework-seleniumtestability==1.1.0
    - rpaframework==7.4.1
    - rpaframework-core==5.3.0
    - rsa==4.7
    - selenium==3.141.0
    - simple-salesforce==1.10.1
    - six==1.15.0
    - sortedcontainers==2.3.0
    - soupsieve==2.1
    - tqdm==4.56.0
    - tweepy==3.10.0
    - tzdata==2021.1
    - tzlocal==2.1
    - uritemplate==3.0.1
    - urllib3==1.26.2
    - webdrivermanager==0.9.0
    - wrapt==1.12.1
    - xlrd==1.2.0
    - xlutils==2.0.0
    - xlwt==1.3.0
    - zeep==4.0.0
rccPostInstall:
  - rfbrowser init